# Generated by Django 3.1.5 on 2021-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pasta', models.IntegerField(default=0)),
                ('comenzo_a_estafar_en', models.DateField()),
                ('canal', models.URLField()),
            ],
        ),
    ]
