# Generated by Django 3.1.5 on 2021-02-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_youtuber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='comenzo_a_estafar_en',
            field=models.DateField(null=True),
        ),
    ]
